language : android
jdk : oraclejdk8
env:
  global :
    - ANROID_API_LEVEL = 26
    - ANDROID_BUILD_TOOLS_VERSION = 26.1.0
android :
  components :
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android - $ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
  licences :
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script :
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./licenses/* "$ANDROID_HOME/licenses"
script :
    - ./gradlew build check
before_install:
- chmod +x gradlew